spring:
  application:
    name: main-app

  datasource:
    url: jdbc:postgresql://localhost:5433/globus_db
    username: globus_user
    password: globus
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer